import mongoose from "mongoose";
const listingSchema = new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,

        },
        description:{
            type:String,
            required:true,
        },
        regularprice:{
            type:Number,
            required:true,
        },
        discountedprice:{
            type:Number,
            required:true,
        },
        address:{
            type:String,
            required:true,
        },
        bathrooms:{
            type:Number,
            required:true,
        },
        bedrooms:{
            type:Number,
            required:true,
        },
        furnished:{
            type:Boolean,
            required:true,
        },
        parking:{
            type:Boolean,
            required:true,  
        },
        type:{
            type:String,    
            required:true,
        },
        offer:{
            type:Boolean,
            required:true,
        },
        imageUrls:{
            type:String,
            required:true,
        },
        userid:{
            type:String,
            required:true,
        },
    },
    {
        timestamps:true,
    }
);
const Listing = mongoose.models.Listing || mongoose.model('Listing', listingSchema);
export default Listing;